/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/User/index.vue')['default']
    UserBasicInfo: typeof import('./src/components/User/BasicInfo.vue')['default']
    UserComponent: typeof import('./src/components/UserComponent/index.vue')['default']
  }
}
